services:
  microbin:
    image: Matszwe02/microbin:latest #CHANGE
    restart: always
    ports:
      - "${MICROBIN_PORT}:8080"
    volumes:
      - ./microbin-data:/app/microbin_data
    env_file:
      - .env
